In [1]:
import pandas as pd

In [2]:
# Load the CSV file, skipping the first 2 rows which are metadata
df_referral = pd.read_csv(r"C:\Users\CEL\Desktop\Quantitative Analysis\iKMC\Referral form_17th Sep '24 - 18th Jun '25.csv", skiprows=2)

In [3]:
# Display basic information about the DataFrame
print("DataFrame Info:")
df_referral.info()

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   recordid             15 non-null     object
 1   rf_dof               15 non-null     object
 2   rf_tof               15 non-null     object
 3   rf_research_id       15 non-null     int64
 4   country_id           15 non-null     int64
 5   site_id              15 non-null     int64
 6   rf_facility_id       15 non-null     int64
 7   rf_facility_sp       2 non-null      object
 8   rf_facility_typ      1 non-null      float64
 9   rf_mom_name          15 non-null     object
 10  rf_mom_age           15 non-null     int64
 11  rf_hospid            15 non-null     object
 12  rf_ga_1              15 non-null     int64
 13  rf_sngl_mltpl        15 non-null     int64
 14  rf_order             0 non-null      float64
 15  rf_dob_1             15 non-null     object
 16  rf_tob_1             15 non-null     object
 17  rf_weight_1          15 non-null     int64
 18  rf_bsex_1            15 non-null     int64
 19  rf_reason_1          15 non-null     int64
 20  rf_reason_spy_1      12 non-null     object
 21  rf_trprt_1           15 non-null     int64
 22  rf_trprt_how_1       15 non-null     int64
 23  rf_trprt_othr_spy_1  0 non-null      float64
 24  rf_mc_sm             15 non-null     int64
 25  rf_mc_mrfrl          15 non-null     int64
 26  rf_mc_mrf_wb         15 non-null     int64
 27  rf_mc_mrf_nwbwhy     2 non-null      object
 28  rf_mc_rfrld          15 non-null     object
 29  rf_mc_rfrlf          15 non-null     object
dtypes: float64(3), int64(15), object(12)
memory usage: 3.6+ KB

In [4]:
# Display the first few rows of the DataFrame
print("\nFirst 5 rows of the DataFrame:")
print(df_referral.head())

First 5 rows of the DataFrame:
     recordid      rf_dof    rf_tof  rf_research_id  country_id  site_id  \
0  B121601639  2025-03-05  10:16:00            1216          11      112
1  B121600387  2025-03-08  10:59:00            1216          11      112
2  B121602462  2025-03-20  11:19:00            1216          11      112
3  B121602463  2025-03-20  11:34:00            1216          11      112
4  B121602710  2025-04-01  17:22:00            1216          11      112

   rf_facility_id rf_facility_sp  rf_facility_typ rf_mom_name  ...  \
0               0    CHC Bamheta              NaN      Shital  ...
1          120002            NaN              NaN       Pooja  ...
2          120004            NaN              NaN    Vishakha  ...
3          120004            NaN              NaN     Manisha  ...
4          120005            NaN              NaN       Madhu  ...

              rf_reason_spy_1 rf_trprt_1  rf_trprt_how_1  rf_trprt_othr_spy_1  \
0                    Asphyxia         12              12                  NaN
1                    Asphyxia         12              12                  NaN
2                         NaN         12              12                  NaN
3  Meconium stained, Asphyxia         12              12                  NaN
4                         NaN         12              12                  NaN

   rf_mc_sm rf_mc_mrfrl rf_mc_mrf_wb  rf_mc_mrf_nwbwhy  rf_mc_rfrld  \
0        11          12           11               NaN   2024-12-21
1        11          12           11               NaN   2024-09-19
2        11          12           11               NaN   2025-01-22
3        11          12           11               NaN   2025-01-26
4        11          11           11               NaN   2024-12-30

   rf_mc_rfrlf
0     10:00:00
1     19:00:00
2     10:00:00
3     18:00:00
4     05:30:00

[5 rows x 30 columns]

In [5]:
df_referral

,recordid,rf_dof,rf_tof,rf_research_id,country_id,site_id,rf_facility_id,rf_facility_sp,rf_facility_typ,rf_mom_name,...,rf_reason_spy_1,rf_trprt_1,rf_trprt_how_1,rf_trprt_othr_spy_1,rf_mc_sm,rf_mc_mrfrl,rf_mc_mrf_wb,rf_mc_mrf_nwbwhy,rf_mc_rfrld,rf_mc_rfrlf
0,B121601639,2025-03-05,10:16:00,1216,11,112,0,CHC Bamheta,NaN,Shital,...,Asphyxia,12,12,NaN,11,12,11,NaN,2024-12-21,10:00:00
1,B121600387,2025-03-08,10:59:00,1216,11,112,120002,NaN,NaN,Pooja,...,Asphyxia,12,12,NaN,11,12,11,NaN,2024-09-19,19:00:00
2,B121602462,2025-03-20,11:19:00,1216,11,112,120004,NaN,NaN,Vishakha,...,NaN,12,12,NaN,11,12,11,NaN,2025-01-22,10:00:00
3,B121602463,2025-03-20,11:34:00,1216,11,112,120004,NaN,NaN,Manisha,...,"Meconium stained, Asphyxia",12,12,NaN,11,12,11,NaN,2025-01-26,18:00:00
4,B121602710,2025-04-01,17:22:00,1216,11,112,120005,NaN,NaN,Madhu,...,NaN,12,12,NaN,11,11,11,NaN,2024-12-30,05:30:00
5,B121602847,2025-04-05,16:33:00,1216,11,112,120005,NaN,NaN,Jyoti,...,NaN,12,12,NaN,11,12,12,C-section,2025-01-25,16:00:00
6,B121602848,2025-04-05,16:44:00,1216,11,112,120005,NaN,NaN,Soniya,...,Asphyxia,12,12,NaN,11,12,12,NaN,2025-01-16,08:50:00
7,B121602851,2025-04-05,16:56:00,1216,11,112,120005,NaN,NaN,Pooja Kumari,...,Respiratory Distress,12,12,NaN,11,12,12,NaN,2025-01-20,11:00:00
8,B121602689,2025-04-05,17:09:00,1216,11,112,120005,NaN,NaN,Parvesh,...,Cry continuously,12,12,NaN,11,12,11,NaN,2024-12-29,07:00:00
9,B121603185,2025-04-23,11:25:00,1216,11,112,0,CHC Loni,NaN,Preeti,...,"Congenital Anomalies,Spina Bifida",12,12,NaN,11,12,11,NaN,2024-12-23,16:00:00
10,B121604702,2025-06-12,11:32:00,1216,11,112,120005,NaN,NaN,Shameena,...,"LBW, Premature",12,12,NaN,11,12,12,NaN,2025-04-07,12:00:00
11,B121604676,2025-06-12,09:54:00,1216,11,112,120005,NaN,NaN,Raheel,...,"Axphysia, LBW, Not cry at birth",12,12,NaN,11,12,12,NaN,2025-04-01,03:00:00
12,B123100002,2025-06-14,15:26:00,1231,11,112,120007,NaN,12.0,RAJKUMARI,...,PRE MATURE,12,13,NaN,11,11,12,OBSERVATION,2025-05-16,02:30:00
13,B121604852,2025-06-16,11:16:00,1216,11,112,120005,NaN,NaN,Rubi,...,"Premature, LBW",12,12,NaN,11,12,12,NaN,2025-02-09,20:00:00
14,B121604885,2025-06-17,10:41:00,1216,11,112,120005,NaN,NaN,Shabana,...,Axphysia,12,12,NaN,11,12,12,NaN,2025-02-19,14:00:00

In [6]:
# Calculate descriptive statistics for numerical columns
print("\nDescriptive Statistics for Numerical Columns:")
print(df_referral.describe())

Descriptive Statistics for Numerical Columns:
       rf_research_id  country_id  site_id  rf_facility_id  rf_facility_typ  \
count       15.000000        15.0     15.0       15.000000              1.0
mean      1217.000000        11.0    112.0   104004.133333             12.0
std          3.872983         0.0      0.0    42225.571174              NaN
min       1216.000000        11.0    112.0        0.000000             12.0
25%       1216.000000        11.0    112.0   120004.000000             12.0
50%       1216.000000        11.0    112.0   120005.000000             12.0
75%       1216.000000        11.0    112.0   120005.000000             12.0
max       1231.000000        11.0    112.0   120007.000000             12.0

       rf_mom_age    rf_ga_1  rf_sngl_mltpl  rf_order  rf_weight_1  rf_bsex_1  \
count   15.000000  15.000000           15.0       0.0    15.000000  15.000000
mean    26.733333  36.666667           11.0       NaN  2330.333333  11.400000
std      5.105553   2.870208            0.0       NaN   655.248444   0.507093
min     20.000000  31.000000           11.0       NaN  1063.000000  11.000000
25%     23.500000  36.000000           11.0       NaN  1870.500000  11.000000
50%     26.000000  37.000000           11.0       NaN  2340.000000  11.000000
75%     28.000000  39.000000           11.0       NaN  2847.000000  12.000000
max     38.000000  41.000000           11.0       NaN  3213.000000  12.000000

       rf_reason_1  rf_trprt_1  rf_trprt_how_1  rf_trprt_othr_spy_1  rf_mc_sm  \
count    15.000000        15.0       15.000000                  0.0      15.0
mean     15.400000        12.0       12.066667                  NaN      11.0
std       1.404076         0.0        0.258199                  NaN       0.0
min      12.000000        12.0       12.000000                  NaN      11.0
25%      16.000000        12.0       12.000000                  NaN      11.0
50%      16.000000        12.0       12.000000                  NaN      11.0
75%      16.000000        12.0       12.000000                  NaN      11.0
max      16.000000        12.0       13.000000                  NaN      11.0

       rf_mc_mrfrl  rf_mc_mrf_wb
count    15.000000     15.000000
mean     11.866667     11.533333
std       0.351866      0.516398
min      11.000000     11.000000
25%      12.000000     11.000000
50%      12.000000     12.000000
75%      12.000000     12.000000
max      12.000000     12.000000

In [7]:
# Check for missing values and their percentages
print("\nMissing Values and their Percentages:")
missing_values = df_referral.isnull().sum()
missing_percentage = (df_referral.isnull().sum() / len(df_referral)) * 100
missing_df = pd.DataFrame({'Missing Count': missing_values, 'Missing Percentage': missing_percentage})
print(missing_df[missing_df['Missing Count'] > 0].sort_values(by='Missing Percentage', ascending=False).to_markdown(numalign="left", stralign="left"))

Missing Values and their Percentages:
|                     | Missing Count   | Missing Percentage   |
|:--------------------|:----------------|:---------------------|
| rf_trprt_othr_spy_1 | 15              | 100                  |
| rf_order            | 15              | 100                  |
| rf_facility_typ     | 14              | 93.3333              |
| rf_facility_sp      | 13              | 86.6667              |
| rf_mc_mrf_nwbwhy    | 13              | 86.6667              |
| rf_reason_spy_1     | 3               | 20                   |

In [8]:
# Analyze unique values and their counts for a few selected categorical/identifier columns that seem relevant
print("\nUnique Values and Counts for selected columns:")
for col in ['country_id', 'site_id', 'rf_reason_1', 'rf_bsex_1', 'rf_trprt_1', 'rf_mc_sm', 'rf_mc_mrfrl', 'rf_mc_mrf_wb', 'rf_sngl_mltpl']:
    if col in df_referral.columns:
        print(f"\n--- {col} ---")
        print(df_referral[col].value_counts().to_markdown(numalign="left", stralign="left"))

Unique Values and Counts for selected columns:

--- country_id ---
| country_id   | count   |
|:-------------|:--------|
| 11           | 15      |

--- site_id ---
| site_id   | count   |
|:----------|:--------|
| 112       | 15      |

--- rf_reason_1 ---
| rf_reason_1   | count   |
|:--------------|:--------|
| 16            | 12      |
| 12            | 2       |
| 15            | 1       |

--- rf_bsex_1 ---
| rf_bsex_1   | count   |
|:------------|:--------|
| 11          | 9       |
| 12          | 6       |

--- rf_trprt_1 ---
| rf_trprt_1   | count   |
|:-------------|:--------|
| 12           | 15      |

--- rf_mc_sm ---
| rf_mc_sm   | count   |
|:-----------|:--------|
| 11         | 15      |

--- rf_mc_mrfrl ---
| rf_mc_mrfrl   | count   |
|:--------------|:--------|
| 12            | 13      |
| 11            | 2       |

--- rf_mc_mrf_wb ---
| rf_mc_mrf_wb   | count   |
|:---------------|:--------|
| 12             | 8       |
| 11             | 7       |

--- rf_sngl_mltpl ---
| rf_sngl_mltpl   | count   |
|:----------------|:--------|
| 11              | 15      |